server:
  port: ${PORT:8762}  # Puerto configurado mediante variable de entorno

## Configuración de Eureka
eureka:
  instance:
    preferIpAddress: true
    hostname: ${HOSTNAME:localhost}  # Hostname configurado mediante variable de entorno
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: ${EUREKA_SERVER_URL:http://localhost:8761/eureka}  # URL de Eureka configurada mediante variable de entorno

## Configuración de Spring Cloud Gateway
spring:
  application:
    name: ${APPLICATION_NAME:gateway}  # Nombre de la aplicación configurado mediante variable de entorno
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
      globalcors:
        cors-configurations:
          '[/**]':
            allowed-origins: "${ALLOWED_ORIGINS:*}"  # Orígenes permitidos configurados mediante variable de entorno
            allowed-headers: "*"
            allowed-methods:
              - GET
              - POST
              - PUT
              - PATCH

## Configuración de Actuator
management:
  endpoint:
    gateway:
      enabled: ${ROUTE_TABLES_ENABLED:true}
  endpoints:
    web:
      exposure:
        include:
          - health
          - info
          - gateway